name: Build, Test, Publish

on:
  workflow_dispatch:
  #pull_request:
   # branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: src
      run: dotnet restore 
    - name: Build
      working-directory: src
      run: dotnet build -c Release --no-restore
    - name: Test
      working-directory: src
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Publish
      working-directory: src
      #run: dotnet publish -o Deployable -c Release --self-contained false --arch x64
      run: dotnet publish -o Deployable -c Release --self-contained false
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        local-dir: src/Deployable/
        server-dir: russjester/cookbook/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/logs/**
          **/.well-known/**
          appsettings.Development.json
        dry-run: false
        log-level: verbose
